.\" Manpage for nuseradd.
.\" Contact vivek@nixcraft.net.in to correct errors or typos.
.TH man 8 "06 May 2010" "1.0" "nuseradd man page"
.SH NAME
brtablet \- Tablet Br - Carteira Digital - Laptop Tupiniquim
.SH SYNOPSIS
nuseradd [USERNAME]
.SH DESCRIPTION
brtablet é um software para calibração da Carteira Digital.
.SH OPTIONS
The nuseradd does not take any options. However, you can supply username.

.SH SEE ALSO

.SH BUGS
No known bugs.
.SH AUTHOR
Diego Rodrigo Hachmann (diego_hachmann@hotmail.com)
